name: Heroes
description: Help blood donation efforts

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  collection: 1.14.11
  intl: 0.16.1
  connectivity: 0.4.6+1
  string_scanner: 1.0.5
  url_launcher: 5.2.7
  scoped_model: 1.0.1
  shrine_images: 1.1.2
  flutter_gallery_assets: 0.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/